[
    {
        "domain": ".facebook.com",
        "expirationDate": 1818761725.180163,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ps_l",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1824835563.250461,
        "hostOnly": false,
        "httpOnly": true,
        "name": "datr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "Y7tYaucHr2qxhGhmZEaO84i5"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1798052414.956387,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "0JNRCOdfbxyYY3Mxc.AWeCixtvZ_zOaMHgvaMhYzJhJhbuoK95t4lDK7fj5WFUzWOQTkM.BqWLtj..AAA.0.0.BqtXNI.AWfI7-q4zlJQmJIaImKn8xGCM9U"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1795459561,
        "hostOnly": false,
        "httpOnly": false,
        "name": "vpd",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "v1%3B632x360x2"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1821795559.334012,
        "hostOnly": false,
        "httpOnly": true,
        "name": "xs",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "25%3ApHlxlSmc8T4YlQ%3A2%3A1790259553%3A-1%3A-1"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1821811561,
        "hostOnly": false,
        "httpOnly": false,
        "name": "fbl_st",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "100421862%3BT%3A29837926"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1790612652.344475,
        "hostOnly": false,
        "httpOnly": false,
        "name": "locale",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "fr_FR"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1821795559.332161,
        "hostOnly": false,
        "httpOnly": false,
        "name": "c_user",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "61591618425912"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1790330871,
        "hostOnly": false,
        "httpOnly": false,
        "name": "dpr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "2"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1824835560.296399,
        "hostOnly": false,
        "httpOnly": true,
        "name": "pas",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "61591618425912%3Afywy19tVrP%2C100080077652459%3A8NGxbyEcxV%2C61588944097723%3AAVSiTaOVr4%2C61583745495456%3ATrbCgQgw6a%2C61591480225146%3AtSkjCxuTbn%2C61592864031822%3AmEwpWGk4Df%2C61593715842737%3AruQc56PE6U%2C61594383005046%3AktEuO5H3wn"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1818761725.180593,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ps_n",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1824819559.333718,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sb",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "Y7tYarU2ij6V7J9M04AKXyS9"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1798051561,
        "hostOnly": false,
        "httpOnly": false,
        "name": "wl_cbv",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "v2%3Bclient_version%3A3300%3Btimestamp%3A1790275569"
    }
]
